language: objective-c
osx_image: xcode7.2
sudo: false
xcode_workspace: PusherSwift.xcworkspace
xcode_scheme: PusherSwift
env:
  global:
    - IOS_SDK=iphonesimulator9.2
    - IOS_SCHEME="PusherSwiftTests-iOS"
    - MACOS_SDK=macosx10.11
    - MACOS_SCHEME="PusherSwiftTests-OSX"
    - TVOS_SDK=appletvsimulator9.1
    - TVOS_SCHEME="PusherSwiftTests-tvOS"
  matrix:
    - DESTINATION="OS=9.2,name=iPad 2"         SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=9.2,name=iPad Air"       SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=9.2,name=iPhone 5"       SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=9.2,name=iPhone 6s"      SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=8.4,name=iPhone 6"       SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=8.4,name=iPad Air"       SDK="$IOS_SDK"   SCHEME="$IOS_SCHEME"
    - DESTINATION="OS=9.1,name=Apple TV 1080p" SDK="$TVOS_SDK"  SCHEME="$TVOS_SCHEME"
    - DESTINATION="platform=OS X,arch=x86_64"  SDK="$MACOS_SDK" SCHEME="$MACOS_SCHEME"
before_install:
  - brew update
  - brew install carthage
script:
  - set -o pipefail
  - xcodebuild -version
  - if [ "$SCHEME" == "PusherSwiftTests-OSX" ]; then
      xcodebuild -workspace PusherSwift.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test -enableCodeCoverage YES | xcpretty -tc;
    else
      xcodebuild -workspace PusherSwift.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" test -enableCodeCoverage YES | xcpretty -tc;
    fi
before_deploy:
  - carthage build --no-skip-current --verbose
  - carthage archive PusherSwift
deploy:
  provider: releases
  api_key:
    secure: JX093TPx+8Rvgd58s5KkmQQM0/i2cwSiSfRydqFHmN96wny5DHxxF0GOj/4kERHMS7R/gQYXCDtAoEAe0OP0ULD9PLH9D51G6KZQ1LKQPpzOK4ydJc3o9/CvcSrJpWmgSoGquOH0EITXxR4xaP3QrvmFx5mV48XHuZbMRjUlR8I=
  file:
    - "PusherSwift.framework.zip"
  skip_cleanup: true
  on:
    repo: pusher-community/pusher-websocket-swift
    tags: true
